Repository 2022Letters/backend, pull requests merged in 2022-07, with the labels that each got.

#59 [USER] api문서 코멘트 추가 및 수정
  api/src/main/java/com/bouquet/api/user/web/UserController.java
Labels: Complete, Asking for Review

#63 [MESSAGE] 메시지 컬럼 수정
  api/src/main/java/com/bouquet/api/message/dto/Message.java
  api/src/main/java/com/bouquet/api/message/dto/MessageRequest.java
  api/src/main/java/com/bouquet/api/message/dto/MessageResponse.java
  api/src/main/java/com/bouquet/api/message/repository/MessageRepository.java
  api/src/main/java/com/bouquet/api/message/web/MessageController.java
Labels: Asking for Review

#65 [USER] 카카오 유저 삭제 기능 수정
  api/src/main/java/com/bouquet/api/user/dto/RefreshedTokenInfo.java
  api/src/main/java/com/bouquet/api/user/dto/User.java
  api/src/main/java/com/bouquet/api/user/service/KakaoAuthService.java
  api/src/main/java/com/bouquet/api/user/service/KakaoAuthServiceImpl.java
  api/src/main/java/com/bouquet/api/user/service/UserService.java
  api/src/main/java/com/bouquet/api/user/web/UserController.java
Labels: Complete

#68 [배포] 백엔드 서버 설정 변경
  api/src/main/resources/application.properties
Labels: Complete

#69 [USER] 구글 유저 탈퇴 기능 수정
  api/src/main/java/com/bouquet/api/user/web/UserController.java
Labels: Complete

#77 [COMMON] jwt interceptor
  api/src/main/java/com/bouquet/api/config/NoAuth.java
  api/src/main/java/com/bouquet/api/config/WebConfig.java
  api/src/main/java/com/bouquet/api/interceptor/JWTInterceptor.java
  api/src/main/java/com/bouquet/api/message/web/MessageController.java
  api/src/main/java/com/bouquet/api/post/web/PostController.java
  api/src/main/java/com/bouquet/api/user/service/CustomOAuth2UserService.java
  api/src/main/java/com/bouquet/api/user/web/UserController.java
Labels: Complete

#82 [POST] 게시글 설정 조회 기능 구현
  api/src/main/java/com/bouquet/api/post/dto/PostResponse.java
  api/src/main/java/com/bouquet/api/post/service/PostService.java
  api/src/main/java/com/bouquet/api/post/web/PostController.java
Labels: Asking for Review

#86 [USER] 유저 로그인 기능 수정
  api/src/main/java/com/bouquet/api/interceptor/JWTInterceptor.java
  api/src/main/java/com/bouquet/api/user/dto/User.java
  api/src/main/java/com/bouquet/api/user/service/KakaoAuthServiceImpl.java
  api/src/main/java/com/bouquet/api/user/service/UserService.java
  api/src/main/java/com/bouquet/api/user/web/UserController.java
Labels: Complete

#88 [USER] 유저 로그인 기능 수정
  api/.gitignore
  api/.gradle/7.4.1/executionHistory/executionHistory.lock
  api/.gradle/7.4.1/fileHashes/fileHashes.lock
  api/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  api/src/main/java/com/bouquet/api/user/dto/KakaoUserInfo.java
  api/src/main/java/com/bouquet/api/user/dto/OAuthAttributes.java
  api/src/main/java/com/bouquet/api/user/dto/User.java
  api/src/main/java/com/bouquet/api/user/dto/UserRequest.java
  api/src/main/java/com/bouquet/api/user/dto/UserResponse.java
  api/src/main/java/com/bouquet/api/user/repository/UserRepository.java
  api/src/main/java/com/bouquet/api/user/service/CustomOAuth2UserService.java
  api/src/main/java/com/bouquet/api/user/service/KakaoAuthService.java
  api/src/main/java/com/bouquet/api/user/service/KakaoAuthServiceImpl.java
  api/src/main/java/com/bouquet/api/user/service/UserService.java
  api/src/main/java/com/bouquet/api/user/web/UserController.java
Labels: Complete

#90 [USER] 유저 로그인 기능 수정
  api/.gitignore
  api/src/main/java/com/bouquet/api/user/dto/KakaoUserInfo.java
  api/src/main/java/com/bouquet/api/user/dto/OAuthAttributes.java
  api/src/main/java/com/bouquet/api/user/dto/User.java
  api/src/main/java/com/bouquet/api/user/dto/UserRequest.java
  api/src/main/java/com/bouquet/api/user/dto/UserResponse.java
  api/src/main/java/com/bouquet/api/user/repository/UserRepository.java
  api/src/main/java/com/bouquet/api/user/service/CustomOAuth2UserService.java
  api/src/main/java/com/bouquet/api/user/service/KakaoAuthService.java
  api/src/main/java/com/bouquet/api/user/service/KakaoAuthServiceImpl.java
  api/src/main/java/com/bouquet/api/user/service/UserService.java
  api/src/main/java/com/bouquet/api/user/web/UserController.java
Labels: Complete
