Repository 2022Letters/backend, pull requests merged in 2022-06, with the labels that each got.

#12 [POST] 게시글 1개 조회 기능 구현
  api/src/main/java/com/bouquet/api/post/dto/Category.java
  api/src/main/java/com/bouquet/api/post/dto/Message.java
  api/src/main/java/com/bouquet/api/post/dto/Post.java
  api/src/main/java/com/bouquet/api/post/dto/PostRequest.java
  api/src/main/java/com/bouquet/api/post/dto/PostResponse.java
  api/src/main/java/com/bouquet/api/post/exception/Message.java
  api/src/main/java/com/bouquet/api/post/exception/PostNotFoundException.java
  api/src/main/java/com/bouquet/api/post/repository/Message.java
  api/src/main/java/com/bouquet/api/post/repository/PostRepository.java
  api/src/main/java/com/bouquet/api/post/service/Message.java
  api/src/main/java/com/bouquet/api/post/service/PostService.java
  api/src/main/java/com/bouquet/api/post/web/Message.java
  api/src/main/java/com/bouquet/api/post/web/PostController.java
Labels: Asking for Review

#14 [POST] 게시글 삭제 기능 구현
  api/src/main/java/com/bouquet/api/post/service/PostService.java
  api/src/main/java/com/bouquet/api/post/web/PostController.java
Labels: Asking for Review

#16 [POST] 게시글 수정 기능 구현
  api/src/main/java/com/bouquet/api/post/dto/Post.java
  api/src/main/java/com/bouquet/api/post/service/PostService.java
  api/src/main/java/com/bouquet/api/post/web/PostController.java
Labels: Asking for Review

#7 [MESSAGE] 메시지 생성 기능 구현
  api/src/main/java/com/bouquet/api/message/dto/Message.java
  api/src/main/java/com/bouquet/api/message/dto/MessageRequest.java
  api/src/main/java/com/bouquet/api/message/dto/MessageResponse.java
  api/src/main/java/com/bouquet/api/message/exception/Message.java
  api/src/main/java/com/bouquet/api/message/exception/MessageNotFoundException.java
  api/src/main/java/com/bouquet/api/message/repository/Message.java
  api/src/main/java/com/bouquet/api/message/repository/MessageRepository.java
  api/src/main/java/com/bouquet/api/message/service/Message.java
  api/src/main/java/com/bouquet/api/message/service/MessageService.java
  api/src/main/java/com/bouquet/api/message/web/Message.java
  api/src/main/java/com/bouquet/api/message/web/MessageController.java
Labels: Error, Asking for Review

#19 feat: 카테고리 변수 이름 수정
  api/src/main/java/com/bouquet/api/post/dto/Category.java
Labels: Asking for Review

#24 [MESSAGE] 메시지 목록 조회 기능 생성
  api/src/main/java/com/bouquet/api/message/dto/MessageResponse.java
  api/src/main/java/com/bouquet/api/message/repository/MessageRepository.java
  api/src/main/java/com/bouquet/api/message/service/MessageService.java
  api/src/main/java/com/bouquet/api/message/web/MessageController.java
Labels: Asking for Review

#30 [USER] 유저 구글 로그인 기능 구현
  api/.gitignore
  api/src/main/java/com/bouquet/api/config/SecurityConfig.java
  api/src/main/java/com/bouquet/api/user/dto/KakaoTokenInfo.java
  api/src/main/java/com/bouquet/api/user/dto/KakaoUserInfo.java
  api/src/main/java/com/bouquet/api/user/dto/Message.java
  api/src/main/java/com/bouquet/api/user/dto/OAuthAttributes.java
  api/src/main/java/com/bouquet/api/user/dto/User.java
  api/src/main/java/com/bouquet/api/user/dto/UserRequest.java
  api/src/main/java/com/bouquet/api/user/dto/UserResponse.java
  api/src/main/java/com/bouquet/api/user/repository/Message.java
  api/src/main/java/com/bouquet/api/user/repository/UserRepository.java
  api/src/main/java/com/bouquet/api/user/service/CustomOAuth2UserService.java
  api/src/main/java/com/bouquet/api/user/service/Message.java
  api/src/main/java/com/bouquet/api/user/service/UserService.java
  api/src/main/java/com/bouquet/api/user/web/Message.java
  api/src/main/java/com/bouquet/api/user/web/UserController.java
  api/src/main/resources/application.properties
  api/src/main/resources/static/index.html
Labels: In Progress

#32 [UPDATE] 로직 변경에 따른 메시지 기능 수정
  api/src/main/java/com/bouquet/api/icon/dto/Icon.java
  api/src/main/java/com/bouquet/api/icon/dto/IconResponse.java
  api/src/main/java/com/bouquet/api/icon/exception/IconNotFoundException.java
  api/src/main/java/com/bouquet/api/icon/repository/IconRepository.java
  api/src/main/java/com/bouquet/api/icon/service/IconService.java
  api/src/main/java/com/bouquet/api/icon/web/IconController.java
  api/src/main/java/com/bouquet/api/message/dto/Message.java
  api/src/main/java/com/bouquet/api/message/dto/MessageRequest.java
  api/src/main/java/com/bouquet/api/message/dto/MessageResponse.java
  api/src/main/java/com/bouquet/api/message/service/MessageService.java
  api/src/main/java/com/bouquet/api/message/web/MessageController.java
Labels: Asking for Review

#36 [MESSAGE] 메시지 삭제 기능 구현
  api/src/main/java/com/bouquet/api/message/dto/MessageResponse.java
  api/src/main/java/com/bouquet/api/message/service/MessageService.java
  api/src/main/java/com/bouquet/api/message/web/MessageController.java
Labels: Asking for Review

#39 [USER] 유저 구글, 카카오 로그인 코드 통합
  api/src/main/java/com/bouquet/api/config/WebConfig.java
  api/src/main/java/com/bouquet/api/interceptor/JWTInterceptor.java
  api/src/main/java/com/bouquet/api/user/exception/Message.java
  api/src/main/java/com/bouquet/api/user/exception/UserNotFoundException.java
  api/src/main/java/com/bouquet/api/user/repository/UserRepository.java
  api/src/main/java/com/bouquet/api/user/security/Message.java
  api/src/main/java/com/bouquet/api/user/service/KakaoAuthService.java
  api/src/main/java/com/bouquet/api/user/service/KakaoAuthServiceImpl.java
  api/src/main/java/com/bouquet/api/user/service/UserService.java
  api/src/main/java/com/bouquet/api/user/web/UserController.java
  api/src/main/java/com/bouquet/api/util/JWTUtil.java
  api/src/main/resources/static/img/kakao_login_large_narrow.png
  api/src/main/resources/static/index.html
Labels: Complete

#38 [POST] 게시글 조회 수정
  api/src/main/java/com/bouquet/api/post/dto/Post.java
  api/src/main/java/com/bouquet/api/post/dto/PostResponse.java
  api/src/main/java/com/bouquet/api/post/service/PostService.java
  api/src/main/java/com/bouquet/api/post/web/PostController.java
Labels: Asking for Review

#41 [POST] TIMESTAMP 변환 기능 생성
  api/src/main/java/com/bouquet/api/post/dto/Post.java
  api/src/main/java/com/bouquet/api/post/dto/PostResponse.java
  api/src/main/java/com/bouquet/api/post/service/PostService.java
Labels: Asking for Review

#42 [UPDATE] 메시지 생성 컬럼 수정
  api/src/main/java/com/bouquet/api/message/dto/Message.java
  api/src/main/java/com/bouquet/api/message/dto/MessageResponse.java
Labels: Asking for Review

#43 [USER] jwt 디펜던시 추가 (#31)
  api/build.gradle
Labels: Complete

#45 [User] user 삭제 기능 , jwt 발급
  api/src/main/java/com/bouquet/api/config/SecurityConfig.java
  api/src/main/java/com/bouquet/api/config/WebConfig.java
  api/src/main/java/com/bouquet/api/user/dto/User.java
  api/src/main/java/com/bouquet/api/user/dto/UserResponse.java
  api/src/main/java/com/bouquet/api/user/service/UserService.java
  api/src/main/java/com/bouquet/api/user/web/UserController.java
  api/src/main/java/com/bouquet/api/util/JWTUtil.java
  api/src/main/resources/static/index.html
Labels: Complete

#46 [DOCS] Rest Api 문서 자동화
  api/build.gradle
  api/src/main/java/com/bouquet/api/config/SwaggerConfig.java
  api/src/main/resources/application.properties
Labels: Asking for Review

#49 [POST] 게시글 작성 기능 수정
  api/src/main/java/com/bouquet/api/post/dto/Post.java
  api/src/main/java/com/bouquet/api/post/dto/PostRequest.java
  api/src/main/java/com/bouquet/api/post/dto/PostResponse.java
  api/src/main/java/com/bouquet/api/post/exception/PostNotFoundException.java
  api/src/main/java/com/bouquet/api/post/repository/PostRepository.java
  api/src/main/java/com/bouquet/api/post/web/PostController.java
Labels: Asking for Review

#52 [Post] api문서 코멘트 추가
  api/src/main/java/com/bouquet/api/post/web/PostController.java
Labels: Asking for Review

#53 [USER] api문서 코멘트 추가
  api/src/main/java/com/bouquet/api/user/web/UserController.java
Labels: Complete
